### ISSUE TITLE
Set graph width to 100%

### ISSUE THREAD

**Issue by fabiankaimer** [QingWei-Li/laue#2]
Is there a possibility to set the width of the "la-cartesian" component to 100% width of the parent element instead of passing the value as pixels?

Good work by the way, I really appreciate your project!

**Comment by QingWei-Li** [comment]
https://laue.js.org/examples#responsive

**Comment by fabiankaimer** [comment]
Oh, seems like I missed it in the docs. Thank you for the quick reply!
