### ISSUE TITLE
la-x-axis and la-y-axis not showing

### ISSUE THREAD

**Issue by maverickchangithub** [QingWei-Li/laue#21]
i just copied your sample code to my project ,  chart is ok , but  x and y axis and tooltip not showing .

**Comment by Aspedm** [comment]
I have same problem. I could not find a solution how to fix, but it solved. May be this helpful for someone.
If you use on demand import, you mast import 
`import { Cartesian, Line, XAxis, YAxis, Tooltip } from 'laue';`

**Comment by hkeidesen** [comment]
And also remember to register it properly:
`
import { Cartesian, Line, XAxis, YAxis } from 'laue';
...
components: {
    LaLine: Line,
    LaCartesian: Cartesian,
    LaXAxis: XAxis,
    LaYAxis: YAxis,
  },
`
