### ISSUE TITLE
Chart won't render if all values are 0

### ISSUE THREAD

**Issue by sauladam** [QingWei-Li/laue#22]
Only tested this with Line and Area charts:

If all values are 0, the chart's SVG-path is not rendered properly because it has a bunch of `NaN`s in it, like so:

```xml
<path 
    stroke="#3fb1e3" 
    fill="none" 
    stroke-width="1" 
    style="stroke-dasharray: none; transition: none 0s ease 0s;"     
    d="M0,NaNC0,NaN,38.09375,NaN,57.140625,NaNC76.1875,NaN,95.234375,NaN,114.28125,NaNC133.328125,NaN,152.375,NaN,171.421875,NaNC190.46875,NaN,209.515625,NaN,228.5625,NaNC247.609375,NaN,266.65625,NaN,285.703125,NaNC304.75,NaN,323.796875,NaN,342.84375,NaNC361.890625,NaN,399.984375,NaN,399.984375,NaN">
</path>
```

There's probably just an issue with the math somewhere. As long as at least 1 value is not 0, everything works fine.

I hope it's an easy fix and will be fixed soon. Thank you for this awesome library!

**Comment by jaunt** [comment]
I also noticed that the same problem results if all y values are the same, regardless if they are zero or not.  I think it's the autoscaling feature.  I haven't tried to reproduce this bug in 0.2.0 yet.

**Comment by dvago** [comment]
The problem is around the `curPoints` computed property of the `Cartesian.js`, line **32** and **33**
Apparently every time the values are 0.something both `y` and `y0` return NaN

```js
        const y = isNaN(end) ? null : y1 - (end - low) * yRatio
        const y0 = isNaN(start) ? null : y1 - (start - low) * yRatio
```

These statements runs into the `else` and the `else` returns NaN
You can edit the code with something like:

```js
if (isNaN(y)) {
          y = 0
        }
        if (isNaN(y0)) {
          y0 = 0
        }
        if (isNaN(x)) {
          x = 0
        }
```
to avoid console errors but the graph doesn't look right.

**Comment by dvago** [comment]
Further investigation tells me that yRatio has `Infinity` as value which clearly creates problem when the logic tries to multiply for a String

**Comment by dvago** [comment]
Solved with: 

```
if (yRatio === Infinity) {
     yRatio = 1
}
```

Line **835** of `laue.js` from the dist folder

or 

Line **31** of `cartesian.js`
