### ISSUE TITLE
Can a small working demo project be in the repo for newbie users to see exactly what is going where?

### ISSUE THREAD

**Issue by zillazillazilla** [QingWei-Li/laue#8]
I'm attempting to get the chart running in Chrome Version 68.0.3440.84 with not much luck at all.

I'm getting '**_Unexpected Identifier_**' in Chrome Version 68 for imports/exports and transpiler wont fix it, using script type="module" only causes further issues such as '**_Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../"._**', however I feel that this may be due to me misinterpreting the setup. 

A small demo project in the repo that users can download with only the minimal required html/js needed to produce the graph locally/on my server would be of great assistance. I know I must be missing something painstakingly obvious to get this running, so seeing a working setup would be great

**Comment by QingWei-Li** [comment]
A dead simple demo

```html
<div id="app">
	<la-cartesian :width="300" :height="150" :data="values">
    <la-line prop="pv"></la-line>
    <la-y-axis></la-y-axis>
    <la-x-axis prop="name"></la-x-axis>
    <la-tooltip></la-tooltip>
  </la-cartesian>
</div>

<script src="//unpkg.com/vue"></script>
<script src="//unpkg.com/laue"></script>
<script>
	new Vue({
		el: '#app',
		data: () => ({
	    values: [
	      { name: 'Page A', pv: 2000 },
	      { name: 'Page B', pv: 3000 },
	      { name: 'Page C', pv: 1200 }
	    ]
	  })
	})
</script>
```

**Comment by zillazillazilla** [comment]
That did it, thanks. Looking forward to expanding from vue-trends to these full charts
